# Generated by Django 6.0.3 on 2026-03-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_prescription_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
