# Generated by Django 6.0.3 on 2026-03-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_medication_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='frequency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
