# Generated by Django 6.0.3 on 2026-05-12 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_alter_appointment_status'),
        ('doctors', '0004_alter_doctorschedule_day_of_week'),
        ('patients', '0006_alter_familymedicalhistory_relation_allergy'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_response', models.TextField()),
                ('predicted_specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_checks', to='patients.patient')),
                ('recommended_doctors', models.ManyToManyField(blank=True, related_name='recommended_symptom_checks', to='doctors.doctor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
