# Generated by Django 6.0.3 on 2026-03-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_height_patient_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
