# Generated by Django 6.0.3 on 2026-03-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_medicalhistory_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
