# Generated by Django 6.0.3 on 2026-03-12 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_medicalhistory_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('sibling', 'Sibling'), ('grandparent', 'Grandparent'), ('other', 'Other')], max_length=50)),
                ('condition', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_medical_history', to='patients.patient')),
            ],
        ),
    ]
