# Generated by Django 6.0.3 on 2026-03-12 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_familymedicalhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymedicalhistory',
            name='relation',
            field=models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('sibling', 'Sibling'), ('grandparent', 'Grandparent')], max_length=50),
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.patient')),
            ],
        ),
    ]
